### ISSUE TITLE
Failed to init client: kubernetes configuration invalid

### ISSUE THREAD

**Issue by fotto1** [oboukili/terraform-provider-argocd#134]
I use an AWS eks cluster and do the autentication via a service token. Configuration is done in a kubectl configuration file, which was tested with kubectl and terraform kubernetes provider, without any issues. But when I use the configuration file in argocd provider I receive following error message:

```
Error: Failed to init clients
│
│   with argocd_repository.gitops,
│   on argocd.config.tf line 42, in resource "argocd_repository" "gitops":
│   42: resource "argocd_repository" "gitops" {
│
│ invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

kubeconfig file
```
apiVersion: v1
kind: Config
current-context: arn:aws:eks:eu-central-1:<account-id>:cluster/<eks-cluster-name>
contexts:
- name: arn:aws:eks:eu-central-1:<account-id>:cluster/<eks-cluster-name>
  context:
    cluster:arn:aws:eks:eu-central-1:<account-id>:cluster/<eks-cluster-name>
    user: myUser
    namespace: kube-system
clusters:
- name: arn:aws:eks:eu-central-1:<account-id>:cluster/<eks-cluster-name>
  cluster:
    certificate-authority-data: "<ca-certificate>"
    server: https://<eks-cluster-id>.gr7.eu-central-1.eks.amazonaws.com
users:
- name: myUser
  user:
    token: <my-token>
```

terraform version:
```log
Terraform v1.1.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/kubernetes v2.7.1
+ provider registry.terraform.io/oboukili/argocd v2.2.1
```

provider configuration:
```terraform
# kubernetes configuration

provider "kubernetes" {
  config_path = var.kubeconfig
}

# argocd configuration

data "kubernetes_secret" "argocd_admin_password" {
  metadata {
    name = "argocd-initial-admin-secret"
    namespace = "argo"
  }
}

provider "argocd" {
  server_addr = "localhost:8443"
  insecure = true
  port_forward = true
  port_forward_with_namespace = "argo"
  username = "admin"
  password = lookup(data.kubernetes_secret.argocd_admin_password.data,"password","")
  kubernetes {
    config_path = var.kubeconfig
  }
}
```

When I leave everything configured as it is run 'aws eks update-kubeconfig' and after that 'terraform apply' I get following result:
```
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
