### ISSUE TITLE
Missing support for `fileParameters` ?

### ISSUE THREAD

**Issue by musabmasood** [oboukili/terraform-provider-argocd#195]
Seems like we're missing support for `fileParameters` in helm source:

```yaml
source:
  helm:
    fileParameters:
      - name: some.key
        path: some/path.yaml
```
