### ISSUE TITLE
Add suport for `exclude` and `include` for argocd_application

### ISSUE THREAD

**Issue by Eric-Fontana-Indico** [oboukili/terraform-provider-argocd#208]
As documented here:

https://github.com/argoproj/argo-cd/issues/10880

example with `exclude`:

```yaml
roject: default
source:
  repoURL: 'https://github.com/crenshaw-dev/directory-app'
  path: .
  targetRevision: HEAD
  directory:
    recurse: true
    jsonnet: {}
    exclude: '{cm1.yaml,cm2.yaml,a-directory/*}'
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
```
