### ISSUE TITLE
Support Plugin Parameters

### ISSUE THREAD

**Issue by addisonj** [oboukili/terraform-provider-argocd#286]
### Description

Since ArgoCD 2.6, the Application CRD supports "paremters" within the plugin block. Currently, this operator doesn't support passing that to the CRD.

An example of parameters:

```Yaml
source:
  repoURL: 'git@github.com:myrepo/repo'
  path: folder
  targetRevision: main
  plugin: # support we have a 
    parameters:
      - name: arrayparam
        array:
          - foo
          - bar
      - name: stringparam
        string: beepboop
``` 

### Potential Terraform Configuration

In terraform, that could be translated literally

```hcl
spec {
  plugin {
    parameter {
      name: "arrayparam"
      array: [ "foo", "bar" ]
    }
    parameter {
      name: "stringparam"
      string: "beepboop"
    }
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
