### ISSUE TITLE
In version 5.x you can use local_config with server_address in 6.x is not possible

### ISSUE THREAD

**Issue by marcelobartsch** [oboukili/terraform-provider-argocd#322]
### Terraform Version, ArgoCD Provider Version and ArgoCD Version

```
Terraform version: v1.5.0
ArgoCD provider version: v6.0.1
ArgoCD version: 2.7.9
```

### Terraform Configuration Files
```hcl
provider "argocd" {
  server_addr      = "argo.server"
  use_local_config = true
  grpc_web         = true
}
```

### Steps to Reproduce

using the above config in 5.x works OK, in 6.x reports this

```
│ Error: Invalid Attribute Combination
│ 
│   with provider["registry.terraform.io/oboukili/argocd"],
│   on main.tf line 23, in provider "argocd":
│   23:   server_addr      = "aargo.server"
│ 
│ These attributes cannot be configured together: [port_forward,port_forward_with_namespace,server_addr,use_local_config,core]

```
### Expected Behavior

allow to use local_config with server_address
### Important Factoids

we have multiple argo servers and we use server_address to point to the one we need to create the resources depending on the code using our local token which is obtained by DEX, so put the AuthToken in the code is painful.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by onematchfox** [comment]
Hi @marcelobartsch,

This change was intentional and should have been highlighted in the release notes (my bad!). The server address was ultimately redundant when using local config since it is sourced from the config file itself (see example config below).

```
contexts:
- name: localhost:8080
  server: localhost:8080
  user: localhost:8080
current-context: localhost:8080
servers:
- grpc-web-root-path: ""
  insecure: true
  server: localhost:8080
users:
- auth-token: eyJhbGcxxx
  name: localhost:8080
```

As such, you can simply remove the `server_addr` from the provider configuration, and everything should work fine. I have updated the release notes to call out this change explicitly. If this doesn't work for you, then please let me know, and we can re-open this issue.
