### ISSUE TITLE
How should pass a variable to the values

### ISSUE THREAD

**Issue by zerr0s** [oboukili/terraform-provider-argocd#373]
Hello,

I'm trying to deploy an app that needs some secrets into an **extraInitContainers** parameter.

```yaml
extraInitContainers: |
  - name: init-providers
    image: busybox:1.36
    imagePullPolicy: IfNotPresent
    command:
      - sh
    args:
      - -c
      - |
        wget --header "Private-Token: <GITLAB PRIVATE TOKEN>" "https://gitlab.com/xxxx" -O /xxxx.jar
```

The argocd application looks like this:

```hcl
resource "argocd_application" "myapp" {
  metadata {
    name      = "myapp"
    namespace = "argocd"
    labels = {
      deployment : "terraform"
    }
    annotations = {
      managed-by : "terraform"
      type : "xxxx"
      deployRepository : "https://gitlab.com/xxxx"
    }
  }

  spec {
    project = "services"
    sync_policy {
      automated {
        prune       = true
        self_heal   = true
        allow_empty = true
      }
      sync_options = [
        "CreateNamespace=true"
      ]
      retry {
        limit = "5"
        backoff {
          duration     = "30s"
          max_duration = "2m"
          factor       = "2"
        }
      }
    }
    destination {
      server    = "https://kubernetes.default.svc"
      namespace = "services"
    }

    source {
      repo_url        = "https://xxxx"
      chart           = "myapp"
      target_revision = "1.1.0"

      helm {
        values = file("${path.module}/manifests/myapp/values.yaml")
      }
    }
  }
}
```

How can I pass a variable to replace GITLAB PRIVATE TOKEN by the variable's value plz ?

I have tried to:

- use parameter definition but helm get an error during templating:

```
rpc error: code = InvalidArgument desc = application spec for myapp is invalid: InvalidSpecError: Unable to generate manifests in .: rpc error: code = Unknown desc = `helm template . --name-template myapp --namespace
│ services --kube-version 1.28 --set extraInitContainers
```

```yaml
parameter {
          name  = "extraInitContainers"
          value = <<-EOT
            |
            - name: init-providers
              image: busybox:1.36
              imagePullPolicy: IfNotPresent
              command:
                - sh
              args:
                - -c
                - |
                  wget --header "Private-Token: <GITLAB PRIVATE TOKEN>" "https://gitlab.com/xxxx" -O /xxxx.jar
          EOT
        }
```

- use values_files + values, but i get another error:

```
pc error: code = InvalidArgument desc = application spec for myapp is invalid: InvalidSpecError: Unable to generate manifests in .: rpc error: code = Unknown desc = `helm template . --name-template myapp --namespace
│ services --kube-version 1.28 --values /tmp/3977a079-c8de-45e2-8ece-80bb957b6231/myapp/manifests/myapp/values.yaml --values /tmp/2ba970eb-770a-43b2-a049-75864316f68c <api versions removed> --include-crds` failed exit
│ status 1: Error: open /tmp/3977a079-c8de-45e2-8ece-80bb957b6231/myapp/manifests/myapp/values.yaml: no such file or directory
```

```yaml
value_files = ["${path.module}/manifests/myapp/values.yaml"]
        values = yamlencode({
          extraInitContainers = <<-EOT
            |
            - name: init-providers
              image: busybox:1.36
              imagePullPolicy: IfNotPresent
              command:
                - sh
              args:
                - -c
                - |
                  wget --header "Private-Token: <GITLAB PRIVATE TOKEN>" "https://gitlab.com/xxxx" -O /xxxx.jar
          EOT
        })
```

Any idea plz ??
