### ISSUE TITLE
Enhancement: Add support for Jsonnet libraries directory

### ISSUE THREAD

**Issue by jabouchleih** [oboukili/terraform-provider-argocd#85]
``For Jsonnet deployments, ArgoCD provides an optional parameter inside the `directory.jsonnet.libs` path. 
The provided parameters can be used to reference the libs directory inside the target repo, so no download of external resources is required. 

The [documentation](https://argoproj.github.io/argo-cd/user-guide/jsonnet/) states that you can either use:
```
  directory:
    jsonnet:
      extVars:
      - name: app
        value: $ARGOCD_APP_NAME
      tlas:
        - name: ns
          value: $ARGOCD_APP_NAMESPACE
      libs:
        - vendor
```
or the ArgoCD CLI: 
```
argocd app create APPNAME \
  --jsonnet-ext-str 'app=${ARGOCD_APP_NAME}' \
  --jsonnet-tla-str 'ns=${ARGOCD_APP_NAMESPACE}' \
  --jsonnet-libs 'vendor'
```

Can this functionality be implemented through the directory, like https://registry.terraform.io/providers/oboukili/argocd/latest/docs/resources/application#ext_var?

Thanks
